In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from matplotlib import pyplot as plt
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, classification_report

In [ ]:
def predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  # x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  return test_acc

In [ ]:
def new_predict(x_test, y_test, weight):
  # This function will take the weight of the trained model and takes decission based on the threshold value
  # Add Intercept
  x_test = add_intercept(x_test)
  y_pred = np.ones(y_test.shape[0])
  hypothesis = np.dot(x_test, weight.T)
  for i in range(0, hypothesis.shape[0]):
    if (hypothesis[i]<0.5):
      y_pred[i] = 0
    if (hypothesis[i]>=0.5):
      y_pred[i] = 1
  test_acc = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred)*100
  recall = recall_score(y_test, y_pred)*100
  f1 = f1_score(y_test, y_pred)*100
  print("Training Accuracy: ", test_acc)
  print("Prescission Score:", precision)
  print("Recall Score : ", recall) 
  print('F1 Score : ', f1)
  print('Confusion Matrix : \n' + str(confusion_matrix(y_test, y_pred)))
  print("Classification Report for 3-classes: ")
  print(classification_report(y_test, y_pred))
  # calculate the overall accuracy
  # print the confussion matrix
  # print the classification report
  return test_acc

In [ ]:
def add_intercept(x):
  intercept = np.ones((x.shape[0], 1))
  return np.concatenate((intercept, x), axis=1)
def perceptron(x_train, y_train, same_weight = False):
  # it uses only the threshold function (basic perceptron)
  # add intercept 
  x_train = add_intercept(x_train)
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  if (same_weight == True): # If we need to do the same weight initilization
    random.seed(10)
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  x_train, y_train = shuffle(x_train, y_train)  # shuffel the training sample
  index = random.randint(0, x_train.shape[0]-1)
  epoch = 1
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      # update the weight
      # w = w + x
      weight = weight + x_train[index]
    if (y_train[index]==0 and hypothesis>=0):
      # update the weight
      # w = w - x
      weight = weight - x_train[index]
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      # now check what is the accuracy now
      score = predict(x_train, y_train, weight)
      if (score*100==100):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

In [ ]:
# OR Gate
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 1, 0, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)


In [ ]:
# AND Gate
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([0, 1, 0, 0])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)


In [ ]:
# NAND gate
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 0, 1, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

In [ ]:
x_train = np.array([[0, 1], [1, 1], [0, 0], [1, 0]])
y_train = np.array([1, 0, 0, 1])
weight  = perceptron(x_train, y_train, same_weight = False)
test_arr = new_predict(x_train, y_train, weight)

In [ ]:
from sklearn import datasets
wine = datasets.load_wine()
# print(wine)

x = wine.data
y = wine.target
print(x.shape)
# print(wine.DESCR)

(178, 13)


In [ ]:
# add intercept / add x0
X = wine.data
def add_intercept(X):
  X= np.hstack([np.ones((X.shape[0],1)), X])
  return X

print(X.shape)
# print(X)
y = add_intercept(X)
# print(y)
print(y.shape)



(178, 13)
(178, 14)


In [ ]:
# # Normalization
# from sklearn import preprocessing
# nor_data = preprocessing.normalize(x)
# print("Before   \n\n",x)
# print("After\n\n",nor_data)


from sklearn.preprocessing import MinMaxScaler
# nor
y = np.array(wine['target'])
my_data = np.array(wine['data'])
# print(my_data)
scaler = MinMaxScaler()
scaler.fit(my_data)
nor_data = scaler.transform(my_data)
# print(my_data)
print(y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
# data after adding x0
print("Before\n\n",nor_data,"\nAfter\n\n")
x_total = add_intercept(nor_data)
y_total = wine.target
print(x_total[0])
print(x_total[1])


Before

 [[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]] 
After


[1.         0.84210526 0.1916996  0.57219251 0.25773196 0.61956522
 0.62758621 0.57383966 0.28301887 0.59305994 0.37201365 0.45528455
 0.97069597 0.56134094]
[1.         0.57105263 0.2055336  0.4171123  0.03092784 0.32608696
 0.57586207 0.51054852 0.24528302 0.27444795 0.26450512 0.46341463
 0.78021978 0.55064194]


[0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1]
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]


In [ ]:
# spliting data  
from sklearn.model_selection import train_test_split
# x_total = nor_x
# y_total = y
X_train,X_test,y_train,y_test = train_test_split(x_total,y_total,test_size = 0.5,random_state = 1)
X_train,X_validation,y_train,y_validation = train_test_split(X_train,y_train,test_size = 0.4,random_state = 1)

# print(X_train.shape)
# print(X_validation.shape)
# print(X_test.shape)
# print(X_train)
# print(y_train)

In [ ]:
# Sigmoid function to bound the hypothesis
def sigmoid(z):                 
    return 1/(1 + np.exp(-z))

# log-loss function
def loss(h, y):                
    return (-y*np.log(h) - (1-y)*np.log(1-h)).mean()


# mean square error
def mse(h, y):                
    return (((h-y)**2).mean())/2

# predict probability
def predict_prob(x):
    return sigmoid(x)

# 
def y_predict(x):
    return predict_prob(x).round()

In [ ]:
# learnig algorithm
# Single layer perceptron(SLP)

def Algorithm(x,y,epoch,rho):
  weight = np.zeros(x.shape[1])
  current_loss = 1  
  error = 0
  # random weight initialization
  for i in range(0, x.shape[1]):
      weight[i] = random.uniform(-0.3, 0.3)
  theta = weight 

  for i in range(epoch):
    # convergence if we reached the max epoch and
    z = np.dot(x[i],theta)
    d = sigmoid(z)
    # gradient
    gradient = np.dot(x.T, (h - y)) / y.size
    theta = theta - alpha * gradient
    z = np.dot(x, theta)
    y_pre = d
    los = loss(h, y)

    


