In [ ]:
#Solution 1.1
import numpy as ny
print('Solution of 1.1 :')
print("Array of 10 zeros : ")
zrs = ny.zeros(10)
print(zrs)
print("Array of 10 ones :")
ones = ny.ones(10)
print(ones)
print("Array of 10 fives :")
fives = ny.ones(10)*5
print(fives)

Solution of 1.1 :
Array of 10 zeros : 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones :
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives :
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# Solution 1.2
print('\nSolution of 1.2: ')
print('All even intergers b/w 10 to 50 ')
even_num = ny.arange(10,50,2)
print(even_num)



Solution of 1.2: 
All even intergers b/w 10 to 50 
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
# Solution 1.3
print('Solution of 1.3 ')
print('Random number b/w 0 and 1')
rnd = ny.random.uniform(0,1)     #uniform is use for 
print(rnd)

Solution of 1.3 
Random number b/w 0 and 1
0.21373701141108403


In [ ]:
# #solution 1.4
print("Solution 1.4") 
rndom = ny.random.rand(3,3)        # for create a random matrix of size 3x3
text_file = open("text.txt", "w")
for row in rndom:
    ny.savetxt(text_file,row)
text_file.close()

mtx = ny.loadtxt("text.txt").reshape(3,3)
print(mtx)

Solution 1.4
[[0.04909855 0.70179174 0.28986388]
 [0.26639503 0.51261776 0.77433616]
 [0.65739125 0.77913454 0.6109573 ]]


In [ ]:
# Solution 2.1
print('Solution od 2.1 : ')
# # using numpy 
# from PIL import Image
# import numpy as pnd
# img = Image.open("Nature.jpg")
# imgtomatx = pnd.asarray(img)
# print(imgtomatx.shape)

# using pandas
from PIL import Image
import pandas as pnd
img = Image.open('nature.jpg')
mtx = pnd.arrays(img)
print(mtx.shape)

In [ ]:
# Solution 2.3
print("\nSolution 2.3 :")
import pandas as pds
from datetime import date
Today_date = pds.to_datetime("today").date()
print("Today's date is :"+str(Today_date))




Solution 2.3 :
Today's date is :2021-08-16


In [ ]:
# Solution 3
from datetime import date
def Age_Cal(DOB):
    Tdate = date.today()
    try:
        bth = DOB.replace(year=Tdate.year)
    except ValueError:
        bth = DOB.replace(year=Tdate.year, month=DOB.month+1,day = 1)
    if bth > Tdate:
        return (Tdate.year - DOB.year - 1)
    else:
        return (Tdate.year - DOB.year)

DOB = input("Enter your DOB  in dd/md/yyyy format : ")
print(Age_Cal(DOB))


Enter your DOB  in dd/md/yyyy format : 12/07/2002


TypeError: ignored