In [ ]:

import numpy as np
import pandas as pd
import random

In [ ]:
# data loading
from sklearn import datasets
iris = datasets.load_iris()
# print(iris)
iris_x = iris.data
y = iris.target
# print(y)

print(iris_x)

In [ ]:
# Normalization. using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
my_data = np.array(iris['data'])
scaler = MinMaxScaler()
scaler.fit(my_data)
nor_x = scaler.transform(my_data)

print(nor_x)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [ ]:
# =====>  Add intercept
def add_intercept(x):
    intr = np.ones((nor_x.shape[0], 1))
    return np.concatenate((intr, nor_x), axis=1)
# now data  is 
x = add_intercept(nor_x)
y = np.array(iris['target'])
# print(x[0])

In [ ]:
# splinting data    train = 30%, test = 50%, validation = 20%
from sklearn.model_selection import train_test_split
x_total = add_intercept(nor_x)
y_total = y

X_train,X_test,y_train,y_test = train_test_split(x_total,y_total,test_size = 0.5,random_state = 1)
X_train,X_validation,y_train,y_validation = train_test_split(X_train,y_train,test_size = 0.4,random_state = 1)

print(X_train.shape)
print(X_validation.shape)
print(X_test.shape)


(45, 5)
(30, 5)
(75, 5)


In [ ]:
# to check classes in dataset
def num_Of_Classes(y):
  l = [0 for i in range(0,100)]
  for i in y:
    l[i] = l[i]+1
  count=0
  classes=[]
  for i in range(0,100):
    if l[i]!=0:
      count=count+1
      classes.append(i)
  return count,classes

# check
numberClasses,classes = num_Of_Classes(iris.target)
print(numberClasses)
print(classes)

3
[0, 1, 2]


In [ ]:
# set y for classifiers 
def onehotencoding(y_data,targetClass):
  y =[]
  for i in y_data:
    if i == targetClass:
      y.append(1)
    else:
      y.append(0)
  return y

# check 
t1 = onehotencoding(y_train,0)
t2 = onehotencoding(y_train,1)
t3 = onehotencoding(y_train,2)
print(t1)
print(t2)
print(t3)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]
[0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]


In [ ]:
def getYs(y,classes):
  ys=[]
  for x in classes:
    ys.append(set_y(y,x))
  return np.array(ys)

In [ ]:
# Sigmoid function to bound the hypothesis
def sigmoid(z):                 
    return 1/(1 + np.exp(-z))

# log-loss function
def loss(h, y):                
    return (-y*np.log(h) - (1-y)*np.log(1-h)).mean()


# mean square error
def mse(h, y):                
    return (((h-y)**2).mean())/2

# predict probability
def predict_prob(x):
    return sigmoid(x)

# 
def y_predict(x):
    return predict_prob(x).round()

In [ ]:
# logistic regression
def train(x,y,epoch,alpha,rho):
    weight = np.zeros(x.shape[1])
    current_loss = 1  
    # random weight initialization
    for i in range(0, x.shape[1]):
        weight[i] = random.uniform(-0.3, 0.3)
    theta = weight 
    # print(weight)
    for i in range(epoch):
        # convergence if we reached the max epoch and
        z = np.dot(x[i],theta)
        # hypothesis
        h = sigmoid(z)         
        gradient = np.dot(x.T, (h - y)) / y.size 

        # new weights
        theta = theta - alpha * gradient
        z = np.dot(x, theta)
        # y_predict
        h = sigmoid(z)
        y_pre = h
        # print(h)
        # log loss error
        los = loss(h, y)  

        # mse error     
        mse_error = mse(h, y) 
        print(f'Epoch: {i} ------> ' + f'Log-Loss: {los} ' + f' ------> Mse: {mse_error} \t ')
        if(abs(current_loss - los) <= rho):
            print(f"Converged through roh criteria: epoch = {i}")
            break # converged
        current_loss = los # save the previous error to calculate the diff in current error and previous error
        if(i + 1 == epoch):
            print("Converged through maximum epoch no criteria...") # converged
    return loss, mse_error

train(X_train,y_train,5,1,0.001)



Epoch: 0 ------> Log-Loss: 0.0891146863171922  ------> Mse: 0.30933411667200905 	 
Epoch: 1 ------> Log-Loss: -0.12971323830726808  ------> Mse: 0.2865390870922515 	 
Epoch: 2 ------> Log-Loss: -0.3158912498923429  ------> Mse: 0.2774649396714229 	 
Epoch: 3 ------> Log-Loss: -0.4771813396740857  ------> Mse: 0.27436653326151866 	 
Epoch: 4 ------> Log-Loss: -0.616164551849638  ------> Mse: 0.27230776657626543 	 
Converged through maximum epoch no criteria...


(<function __main__.loss>, 0.27230776657626543)